options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image and tag it appropriately
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/novaferi/kb-node-v0/nodeapp:${COMMIT_SHA}', '.']

  # Step 2: Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/novaferi/kb-node-v0/nodeapp:${COMMIT_SHA}']

  # Step 3: Get credentials for Kubernetes cluster
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - 'kb-node-minikube-cluster'
    - '--region'
    - 'us-central1'
    - '--project'
    - 'novaferi'

  # Step 4: Update Kubernetes deployment with the new image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: kubectl
    args:
    - 'set'
    - 'image'
    - 'deployment/node-app'
    - 'nodeapp=us-central1-docker.pkg.dev/novaferi/kb-node-v0/nodeapp:${COMMIT_SHA}'
