apiVersion: v1
kind: Service
metadata:
  name: kbnode-app
  namespace: kb-node-minikube-cluster
spec:
  type: ClusterIP
  selector:
    app: kbnode-app
  ports:
    - port: 3000
      targetPort: 3000